version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      deps-dev:
        dependency-type: development
    ignore:
      - dependency-name: oxc-resolver
